/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    java
    scala
    kotlin("jvm") version "1.9.10"
    groovy
    `maven-publish`
    id("io.freefair.lombok") version "8.2.2"
    id("com.github.johnrengelman.shadow") version "8.0.0"
}

group = "dev.frilly"
version = "0.1-SNAPSHOT"

val shade by configurations.creating {
    extendsFrom(configurations.runtimeClasspath.get())
}

repositories {
    mavenCentral()
    mavenLocal()
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots")
}

dependencies {
    testImplementation(kotlin("test"))

    shade("org.ow2.asm:asm:9.5")
    implementation("org.scala-lang:scala3-library_3:3.3.1-RC6")
    implementation("org.apache.groovy:groovy:4.0.14")
    implementation("org.bukkit:bukkit:1.8-R0.1-SNAPSHOT")
}

kotlin {
    jvmToolchain(8)
}

val javadocJar by tasks.register<Jar>("javadocJar") {
    dependsOn(tasks.javadoc.get())
    from(tasks.javadoc.get().destinationDir)
    destinationDirectory.set(file("./build/libs"))
    archiveClassifier.set("javadoc")
}

tasks.shadowJar {
    configurations = listOf(shade)
    isZip64 = true
    relocate("org.ow2.asm", "dev.frilly.hikarilib.asm")
    archiveClassifier.set("shaded")
    minimize()
}

tasks.withType<Jar> {
    archiveBaseName.set("HikariLibrary")
}
